{% set name = "openjd-adaptor-runtime" %}
{% set version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openjd_adaptor_runtime-{{ version }}.tar.gz
  sha256: 58e00c4a08686821df01c736e0781a3736450865cc2cf4e3799e354d324112d8
  patches:
    - 0001-Remove-version-hook.patch

build:
  skip: true  # [py<39]
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9,<3.12
    - pyyaml >=6.0,<7.dev0
    - jsonschema >=4.17.0,<5.0
    - pywin32 ==306  # [win]

test:
  imports:
    - openjd.adaptor_runtime
    - openjd.adaptor_runtime_client
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A python library for building adaptors that integrate applications with Open Job Description jobs.
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
