{% set name = "cinema4d" %}
{% set display_name = "Cinema4D" %}
{% set version_major = "2025" %}
{% set version_minor = "0" %}
{% set version_patch = "2" %}
{% set version = version_major + "." + version_minor + "." + version_patch %}

{% set bucket_name = "your-bucket-name" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: s3://{{ bucket_name }}/{{ display_name }}_{{ version_major }}_{{ version }}_Win.exe # [win64]
  folder: installer

build:
  number: 0
  binary_relocation: False
  detect_binary_files_with_prefix: False
  # The binary is built to be relocatable, so can ignore the warnings about DSOs.
  missing_dso_whitelist:
  - "*"
  ignore_prefix_files: True

test:
 commands:
   # Turning off the test because it seems to try and pull a license even when
   # just printing the help text
   # - Commandline -help

about:
  home: https://www.maxon.net/en/cinema-4d
  license: Commercial
  summary: >
    3D computer animation, modeling, simulation, and rendering software