{% set name = "cinema4d" %}
{% set display_name = "Cinema4D" %}
{% set version_partial = "2025" %}
{% set version_minor = "0" %}
{% set version = version_partial + "." + version_minor %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: s3://byol-example-ja-bucket-686255944943-us-east-2/C4DInstallers/Cinema4D_2025_2025.0.1_Win.exe
  folder: installer

build:
  number: 0
  binary_relocation: False
  detect_binary_files_with_prefix: False
  # The binary is built to be relocatable, so can ignore the warnings about DSOs.
  missing_dso_whitelist:
  - "*"
  ignore_prefix_files: True

test:
 commands:
   # Turning off the test because it seems to try and pull a license even when
   # just printing the help text
   # - Commandline -help

about:
  home: https://www.maxon.net/en/cinema-4d
  license: Commercial
  summary: >
    3D computer animation, modeling, simulation, and rendering software