{% set name = "cinema4d-openjd" %}
{% set version = "0.3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/deadline-cloud-for-cinema-4d/deadline_cloud_for_cinema_4d-{{ version }}.tar.gz
  sha256: 36bc0d81bd40eb1cc0403b06ddbf98a4a6963ecfffb1abaf5caf53891ab0f9c6
  patches:
    - 0001-Remove-version-build-hook.patch
    - 0002-Get-sitepackages-path.patch

## Here's an alternative source definition to build a package from a development branch on github. Replace
## the username and git branch as appropriate for your case.
# source:
  # git_url: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d.git
  # git_rev: region-render

build:
  entry_points:
    - cinema4d-openjd = deadline.cinema4d_adaptor.Cinema4DAdaptor:main
    - Cinema4DAdaptor = deadline.cinema4d_adaptor.Cinema4DAdaptor:main
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9,<3.12
    - deadline ==0.48.*
    - openjd-adaptor-runtime ==0.8.*

test:
  imports:
    - deadline.cinema4d_adaptor
  commands:
    - pip check
    - cinema4d-openjd --help
  requires:
    - pip

about:
  summary: AWS Deadline Cloud for Cinema 4D
  dev_url: https://github.com/aws-deadline/deadline-cloud-for-cinema-4d
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE